Repository hyperwallet/hyperwallet-ios-sdk, pull requests merged in 2019-07, with the labels that each got.

#33 Bugfix/hw 53096 move status back to transfer method query param
  Sources/Model/TransferMethod/HyperwalletBankAccountQueryParam.swift
  Sources/Model/TransferMethod/HyperwalletBankCardQueryParam.swift
  Sources/Model/TransferMethod/HyperwalletPayPalAccountQueryParam.swift
  Sources/Model/TransferMethod/HyperwalletPrepaidCardQueryParam.swift
  Sources/Model/TransferMethod/HyperwalletTransferMethodQueryParam.swift
  Tests/TransferMethod/HyperwalletBankCardTests.swift
Labels: bug

#32 Task/hw 53101 core list transfers
  HyperwalletSDK.xcodeproj/project.pbxproj
  README.md
  Sources/Hyperwallet.swift
  Sources/Model/Transfer/HyperwalletTransfer.swift
  Sources/Model/Transfer/HyperwalletTransferQueryParam.swift
  Tests/Responses/Transfer/ListTransferResponse.json
  Tests/Transfer/HyperwalletTransferTests.swift
Labels: enhancement

#35 HW-53971 Swift upgrade to version 5
  .travis.yml
  HyperwalletSDK.podspec
  HyperwalletSDK.xcodeproj/project.pbxproj
  README.md
Labels: enhancement

#52 Bugfix/hw 54359 transfer to paypal account is mapped to unknown
  Sources/Model/Receipt/HyperwalletReceipt.swift
  Tests/Receipt/HyperwalletReceiptTests.swift
  Tests/Responses/ListPrepaidCardReceiptResponse.json
  Tests/Responses/ListUserReceiptResponse.json
Labels: Depended UI Ticket

#55 Task/hw 54448 make all properties in the model as optional (Depended UI Ticket)
  Sources/Hyperwallet.swift
  Sources/HyperwalletError.swift
  Sources/Model/GraphQL/GraphQlError.swift
  Sources/Model/GraphQL/TransferMethodConfiguration.swift
  Sources/Model/Paging/HyperwalletPageList.swift
  Sources/Model/Receipt/HyperwalletReceipt.swift
  Sources/Model/StatusTransition/HyperwalletStatusTransition.swift
  Tests/GraphQL/TransferMethodConfigurationKeyResultTests.swift
  Tests/Receipt/HyperwalletReceiptTests.swift
  Tests/Transfer/HyperwalletTransferTests.swift
  Tests/TransferMethod/HyperwalletBankAccountTests.swift
  Tests/TransferMethod/HyperwalletBankCardTests.swift
  Tests/TransferMethod/HyperwalletPayPalAccountTests.swift
  Tests/TransferMethod/HyperwalletPrepaidCardTests.swift
  Tests/TransferMethod/HyperwalletTransferMethodTests.swift
Labels: Depended UI Ticket
